name: Integración Continua (CI)
# Configuración de detonadores (eventos)
on:
 push:
 branches: [ "feature/descuento-capuchino" ]
 pull_request:
 branches: [ "feature/descuento-capuchino" ]

# Trabajos a ejecutar en la canalización
jobs:
 build-and-test:
 runs-on: ubuntu-latest
 steps:
 # 1. Descargar el código del repositorio en el servidor de pruebas
 - name: https://github.com/Casandra051020/cloud-coffee-api.git
 uses: actions/Casandra051020
 # 2. Configurar el entorno de ejecución (Ejemplo estándar con

 # 3. Instalar las dependencias del proyecto de forma limpia
 - name: Instalar dependencias
 run: npm ci
 # 4. Ejecutar la suite de pruebas unitarias automatizadas
 - name: Ejecutar pruebas un